### ISSUE TITLE
Unable to configure cypress.json

### ISSUE THREAD

**Issue by captain-yossarian** [browserstack/browserstack-cypress-cli#130]
So, I'm able to connect with dashboard, but it is looks like for some reason my old cypress.json config is wrong

Here is the error:
![cypress-error](https://user-images.githubusercontent.com/16646733/111490365-424b8d80-873b-11eb-8225-d319891a6ddc.png)

I don't understand why `browsers` is required, since all allowed browsers I defined in browserstack.json
My **cypress.json**

```json
{}
```

My **browserstack.json**
```json
{
    "auth": {
        "username": "*****",
        "access_key": "*****"
    },
    "browsers": [
        {
            "browser": "chrome",
            "os": "Windows 10",
            "versions": [
                "latest",
                "latest-1"
            ]
        }
    ],
    "run_settings": {
        "cypress_config_file": "./cypress.json",
        "cypress_version": "5",
        "project_name": "Cypress Kitchen Sink Example",
        "build_name": "Build no: 1",
        "parallels": 5,
        "npm_dependencies": {},
        "specs": ["cypress/integration/functional/**/*"]
      },
    "connection_settings": {
        "local": true
    },
    "disable_usage_reporting": false
}

```

What I'm doing wrong?

I see that you have same cypress.json config in your [example](https://github.com/cypress-io/cypress-example-kitchensink/blob/master/cypress.json)

**Comment by suryart** [comment]
I will encourage you to email the details to support@browserstack.com for any support-related queries/product issues. We're considering issues on this repository for the CLI-related bugs/problems.

Thank you for your understanding. :)
