### ISSUE TITLE
Getting Error : Please contact BrowserStack support for Cypress.

### ISSUE THREAD

**Issue by tanuj-vishnoi** [browserstack/browserstack-cypress-cli#16]
When I run the code with required configuration , I am getting the below errors :
'Please contact BrowserStack support for Cypress.' }
[5/10/2020, 9:37:48 PM]  Zip Upload failed.
[5/10/2020, 9:37:48 PM]  [ERROR] Zip Upload failed.
[5/10/2020, 9:37:48 PM]  undefined

I debugged the source and found the below message came from browser stack cloud server.
Here is the request : 
{ url:
   'https://api-cloud.browserstack.com/automate-frameworks/cypress/upload',
  auth:
   { user: 'xxxxxxxxxx',
     password: 'xxxxxxxxxxxxxxxxx',
     pass: 'xxxxxxxxxxxxxxxxxxxxxxxxxxx' },
  formData:
   { file:
      ReadStream {
        _readableState: [ReadableState],
        readable: false,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        path: 'tests.zip',
        fd: null,
        flags: 'r',
        mode: 438,
        start: undefined,
        end: Infinity,
        autoClose: true,
        pos: undefined,
        bytesRead: 44607,
        closed: true,
        emit: [Function] },
     filetype: 'zip',
     filename: 'tests' } }
and response:

{ error: 'Please contact BrowserStack support for Cypress.' }

**Comment by wati123321** [comment]
Testing with Cypress is currently in the beta phase on the BrowserStack platform. It is available only to subscribed users. You will have to raise a support ticket with BrowserStack for this.
https://www.browserstack.com/contact?ref=help

**Comment by tanuj-vishnoi** [comment]
thank you ! I received the same from BS support team - "Testing with Cypress is currently in the beta phase on our platform. Currently, I don't have an ETA as to when it will be available for all the users.
I will inform you once Cypess testing on BrowserStack is available to the users."

**Comment by suryart** [comment]
Closing the issue as access is not publicly available yet.

**Comment by JShabtai** [comment]
@suryart Would it be possible to add a note in the README point out that this is not public yet?  Since this repo is public, this might cause some confusion (and, apparently, already has).

I think just a small header near the top would go a long way.

**Comment by suryart** [comment]
> @suryart Would it be possible to add a note in the README point out that this is not public yet? Since this repo is public, this might cause some confusion (and, apparently, already has).
> 
> I think just a small header near the top would go a long way.

Point noted. Apologies if this has caused confusion.

**Comment by kartikeypokhriyal7000** [comment]
Just for my clarification , is it not in use for non-subscribed users or any user in general ?

**Comment by suryart** [comment]
> Just for my clarification , is it not in use for non-subscribed users or any user in general ? @suryart

Any user in general. Reach out to sales or your account manager for further assistance on this.

**Comment by suryart** [comment]
An update.

BrowserStack's Cypress support is in Public Beta - https://www.browserstack.com/automate/cypress

Anyone with an Automate account should be able to run Cypress tests on BrowserStack. 🤟
