### ISSUE TITLE
Run cypress tests using the default browser "Electron"

### ISSUE THREAD

**Issue by abhijeetj100** [browserstack/browserstack-cypress-cli#263]
Hi,

I have been working on writing Cypress tests and am running them on BrowserStack using "browserstack-cypress-cli". I just wanted to know if it would be possible to run these tests on cypress's default browser, `Electron`, on BrowserStack instead of Chrome/Edge/Firefox.

Please let me know if this would be possible.

Thanks,
Abhijeet

PS: Apologies if this is the wrong place for this question, kindly let me know if there is a better place where I can ask this question.

**Comment by Jaimin180296** [comment]
@abhijeetj100  You can run the cypress test on BrowserStack on Chrome, Firefox, Edge only. 

You can refer to this link: https://www.browserstack.com/docs/automate/cypress/browsers-and-os
