### ISSUE TITLE
Add option to include additional file types in the .zip archive 

### ISSUE THREAD

**Issue by bingnz** [browserstack/browserstack-cypress-cli#267]
Our project is structured as a monorepo and we have two Cypress projects that use a shared library that's also part of the monorepo.
It'd be useful to be able to package this library locally and reference the .tar.gz file as an npm package, but this isn't one of the file extensions that can be included in the package.
This might also help in working around issues with private npm repositories.

I think it'd be a good addition either to allow additional file extensions as part of the configuration and/or as a CLI option. Failing that, to include .tar.gz as a supported extension (.zip is already supported).

**Comment by bingnz** [comment]
Thanks @nagpalkaran95; that seems like it'll work.

**Comment by nagpalkaran95** [comment]
Yes. Planning to push it in the next cli release. Until then if you are stuck, you can take the latest master pull and run your tests. Let us know if you have use cases of any other file types.

**Comment by nagpalkaran95** [comment]
CLI ver 1.13.0 released with the support for more file types.
