### ISSUE TITLE
Unable to run browserstack-cypress run command on Openshift 

### ISSUE THREAD

**Issue by mrsenzy** [browserstack/browserstack-cypress-cli#286]
Hi Team - 

I have integrated browserstack-cypress-cli with my cypress framework and able to run test scenarios from local IDE to browserstack. While i try to run same command from openshift i get below error - 

/bin/sh: browserstack-cypress: command not found

i checked the presence of node_modules\.bin\browserstack-cypress exist in this path ... still it couldnt find the command for run. 

Any topics discussed on this - Please share me insight on this.

**Comment by pranavj1001** [comment]
Hey @mrsenzy, are you still facing this issue? or this has been resolved?

**Comment by pranavj1001** [comment]
ack, closing this issue then. Please reopen or create a new one if you're facing any other issues.
