### ISSUE TITLE
1.18.0 - Cypress config file not accepting cypress.config.ts 

### ISSUE THREAD

**Issue by mrsenzy** [browserstack/browserstack-cypress-cli#400]
Below is the browserstack.json input provided - but while running test it display error like 

[9/6/2022, 4:40:31 PM] - info: Validating the config
[9/6/2022, 4:40:31 PM] - error: cypress.json is not a valid json
[9/6/2022, 4:40:31 PM] - error: browerstack.json is not valid

{
    "auth": {
        "username": "",
        "access_key": ""
    },
    "browsers": [
        {
            "browser": "chrome",
            "os": "Windows 10",
            "versions": [
                "latest"
            ]
        }
    ],
    "run_settings": {
        "cypress_config_file": "./cypress.config.ts",
        "project_name": "Cypress_BDD",
        "build_name": "Smoke_Test",
        "exclude": [],
        "parallels": "9",
        "specs": [
            "cypress/e2e/*.feature"
        ],
        "cypress_version": "10",
        "npm_dependencies": {
            "hi-cypress": "5.0.0",
            "cypress-log-to-output": "1.1.2",
            "typescript": "4.3.4"
        },
        "package_config_options": {
            "cypress-cucumber-preprocessor": {
                "stepDefinitions": [
                    "cypress/e2e/stepdefinition/**/*.{js,ts}"
                ],
                "json": {
                    "enabled": true
                },
                "html": {
                    "enabled": false
                }
            }
        },
        "headless": false
    },
    "connection_settings": {
        "local": true,
        "local_identifier": "MNX"
    },
    "disable_usage_reporting": false
}

**Comment by sharutkarsh** [comment]
Hey there,

I suppose you are trying to run the Cypress version 10 or above on BrowserStack.

Would request you to please follow this documentation and try the sample project with cypress 10.

Link- https://www.browserstack.com/docs/automate/cypress#Cypress_v10

After trying to run that sample automation script from the document if you face any further issues, please open a support ticket from this link: https://www.browserstack.com/contact?ref=help#technical-support

I hope this helps!

Thanks,
Utkarsh Sharma

**Comment by mrsenzy** [comment]
support ticket raised for this. closing this
