### ISSUE TITLE
Cypress 10 config file imports not working

### ISSUE THREAD

**Issue by KeyanNamaghi** [browserstack/browserstack-cypress-cli#421]
returns `Cannot find module 'cypress'` when running on browserstack and seems to ignore the `npm_dependencies` inside of the `run_settings` in the browserstack.json.

Also having the same issue as others have described when trying to use typescript despite also having added typescript to the `npm_dependencies` too
```
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for ./cypress.config.ts
```

**Comment by CRoulandSpiral** [comment]
I recently ran into the "cannot find module `cypress`" issue as well while browserstack was trying to parse the cypress.config.js for cypress 10. Nothing changed in our config files, tests just started failing. Our workaround was to explicitly list a version of "cypress" as a dependency within the npm_dependencies, but we're not running into any issues of browserstack ignoring the npm_dependencies.
`"npm_dependencies": {
      "cypress": "^10.8.0",`
