### ISSUE TITLE
Fetch polyfill

### ISSUE THREAD

**Issue by reszkapiotr** [browserstack/browserstack-cypress-cli#56]
Hello, I'm facing issue with running tests which includes stubs for fetch. Neither cypress version 5.0.0 with experimentalFetchPolyfill nor 5.0.1 with experimentalNetworkStubbing is working for me.
Could you please advise how this could be fixed?
Thanks

**Comment by shawnlobo96** [comment]
Hey @reszkapiotr 

Are you able to execute a test locally? If not, the same would also apply when executing a test on Browserstack. 

However, if it is only failing on Browserstack but passing locally, could you share the build ID with us on support@browserstack.com?

**Comment by karanshah-browserstack** [comment]
Hi, This should be fixed in v1.6.0 which we released yesterday. Please feel free to reach out to us if you still feel any issues .
