### ISSUE TITLE
How to specify mobile device?

### ISSUE THREAD

**Issue by webunderconstruction** [browserstack/browserstack-cypress-cli#61]
I see the default list of gives you many desktop browsers to test against, but what about mobile devices such as iphone and android?

**Comment by HeenaNanwani8** [comment]
Hey @webunderconstruction, currently you won't be able to execute your Cypress tests on Mobile Browsers on BrowserStack as the same is not supported by Cypress as well.

**Comment by webunderconstruction** [comment]
Thanks for the update @HeenaNanwani8 

Hopefully Browserstack can push hard for cypress / mobile device integration, I feel paying for Browserstack for desktop only isn't getting value for money.
