### ISSUE TITLE
How to run cypress.json file of different name using cypress_proj_dir key other than cypress.json file name

### ISSUE THREAD

**Issue by kalpeshchilka** [browserstack/browserstack-cypress-cli#63]
Currently, I have different cypress.json files for each environment. E.g -  cypress-qa.json and cypress-dev.json. How can we run a specific cypress-env.json file using **"cypress_proj_dir": "./",**.
I am running my tests locally by invoking these cypress-env.json files using the environment specific bash files, as per my build environment need. 
Can we achieve the same using BrowserStack by mentioning specific cypress-env.json file name? Tried different combinations but it throws below mentioned error: 
**error: cypress.json file is not found at cypress_proj_dir path ./**

**Comment by Namrata-m13** [comment]
@kalpeshchilka This feature will be available in the next release of the browserstack-cypress-cli, which is scheduled in the coming weeks.

**Comment by kalpeshchilka** [comment]
Thank you for the update. Awaiting for the new release!

**Comment by suryart** [comment]
This is fixed by #54 

We've released [v1.5.0](https://www.npmjs.com/package/browserstack-cypress-cli/v/1.5.0) with the changes, which supports custom cypress config JSON.

Please see the docs for more details - https://www.browserstack.com/docs/automate/cypress/configuration-file
