### ISSUE TITLE
When a run is started then all files in the project are removed

### ISSUE THREAD

**Issue by iwt-ttaskov** [browserstack/browserstack-cypress-cli#653]
Hi,

something weird happens when I start the browserstack-cypress-cli in my project. I execute this command 'npx browserstack-cypress run --browser chrome --headless' and then all files of my project are deleted as the log shows below.

Why is this happening? I tried with browserstack-cypress-cli versions 1.24.2 and 1.24.3 but I get the same result -> all files are removed :( 

`MC02D61TRMD6R:immonet-qa ttaskov$ npx browserstack-cypress run --browser chrome --headless
[7/14/2023, 9:18:04 PM] - info: Reading config from /Users/ttaskov/immonet_git/github/immonet-qa/browserstack.json
(node:52432) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
[7/14/2023, 9:18:05 PM] - info: Running npx cypress run --browser chrome --headless --reporter browserstack-cypress-cli/bin/testObservability/reporter

DevTools listening on ws://127.0.0.1:63766/devtools/browser/e235043d-2e1e-4de2-ad54-11945c400c04

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:        12.17.1                                                                        │
  │ Browser:        Chrome 114 (headless)                                                          │
  │ Node Version:   v18.16.1 (/Users/ttaskov/.volta/tools/image/node/18.16.1/bin/node)             │
  │ Specs:          5 found (contact.spec.ts, homepage.spec.ts, login.spec.ts, registration.spec.t │
  │                 s, search.spec.ts)                                                             │
  │ Searched:       e2e/**/*.spec.ts                                                               │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘

────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running:  contact.spec.ts                                                                 (1 of 5)

Oops...we found an error preparing this test file:

  > support/e2e.ts

The error was:

Error: Webpack Compilation Error
multi ./support/e2e.ts
Module not found: Error: Can't resolve '/Users/ttaskov/immonet_git/github/immonet-qa/support/e2e.ts' in '/Users/ttaskov/immonet_git/github/immonet-qa'
Looked for and couldn't find the file at the following paths:
[/Users/ttaskov/immonet_git/github/immonet-qa/package.json]
[/Users/ttaskov/immonet_git/github/immonet-qa/support/e2e.ts/package.json]
[/Users/ttaskov/immonet_git/github/immonet-qa/support/e2e.ts]
[/Users/ttaskov/immonet_git/github/immonet-qa/support/e2e.ts.js]
[/Users/ttaskov/immonet_git/github/immonet-qa/support/e2e.ts.json]
[/Users/ttaskov/immonet_git/github/immonet-qa/support/e2e.ts.jsx]
[/Users/ttaskov/immonet_git/github/immonet-qa/support/e2e.ts.mjs]
[/Users/ttaskov/immonet_git/github/immonet-qa/support/e2e.ts.coffee]
[/Users/ttaskov/immonet_git/github/immonet-qa/support/e2e.ts.ts]
[/Users/ttaskov/immonet_git/github/immonet-qa/support/e2e.ts.tsx]
[/Users/ttaskov/immonet_git/github/immonet-qa/Users/ttaskov/immonet_git/github/immonet-qa/support/e2e.ts/package.json]
[/Users/ttaskov/immonet_git/github/immonet-qa/Users/ttaskov/immonet_git/github/immonet-qa/support/e2e.ts]
[/Users/ttaskov/immonet_git/github/immonet-qa/Users/ttaskov/immonet_git/github/immonet-qa/support/e2e.ts.js]
[/Users/ttaskov/immonet_git/github/immonet-qa/Users/ttaskov/immonet_git/github/immonet-qa/support/e2e.ts.json]
[/Users/ttaskov/immonet_git/github/immonet-qa/Users/ttaskov/immonet_git/github/immonet-qa/support/e2e.ts.jsx]
[/Users/ttaskov/immonet_git/github/immonet-qa/Users/ttaskov/immonet_git/github/immonet-qa/support/e2e.ts.mjs]
[/Users/ttaskov/immonet_git/github/immonet-qa/Users/ttaskov/immonet_git/github/immonet-qa/support/e2e.ts.coffee]
[/Users/ttaskov/immonet_git/github/immonet-qa/Users/ttaskov/immonet_git/github/immonet-qa/support/e2e.ts.ts]
[/Users/ttaskov/immonet_git/github/immonet-qa/Users/ttaskov/immonet_git/github/immonet-qa/support/e2e.ts.tsx]
 
    at handle (/Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-preprocessor/dist/index.js:212:23)
    at finalCallback (/Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:257:39)
    at /Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:306:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:304:22
    at Compiler.emitRecords (/Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:499:39)
    at /Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:298:10
    at /Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:482:27
    at /Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/node_modules/neo-async/async.js:2818:7
    at done (/Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/node_modules/neo-async/async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:464:33
    at /Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:143:16
    at /Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:143:16
    at /Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:198:23)

This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.

Oops...we found an error preparing this test file:

  > e2e/contact.spec.ts

The error was:

Error: Webpack Compilation Error
multi ./e2e/contact.spec.ts
Module not found: Error: Can't resolve '/Users/ttaskov/immonet_git/github/immonet-qa/e2e/contact.spec.ts' in '/Users/ttaskov/immonet_git/github/immonet-qa'
Looked for and couldn't find the file at the following paths:
[/Users/ttaskov/immonet_git/github/immonet-qa/package.json]
[/Users/ttaskov/immonet_git/github/immonet-qa/e2e/contact.spec.ts/package.json]
[/Users/ttaskov/immonet_git/github/immonet-qa/e2e/contact.spec.ts]
[/Users/ttaskov/immonet_git/github/immonet-qa/e2e/contact.spec.ts.js]
[/Users/ttaskov/immonet_git/github/immonet-qa/e2e/contact.spec.ts.json]
[/Users/ttaskov/immonet_git/github/immonet-qa/e2e/contact.spec.ts.jsx]
[/Users/ttaskov/immonet_git/github/immonet-qa/e2e/contact.spec.ts.mjs]
[/Users/ttaskov/immonet_git/github/immonet-qa/e2e/contact.spec.ts.coffee]
[/Users/ttaskov/immonet_git/github/immonet-qa/e2e/contact.spec.ts.ts]
[/Users/ttaskov/immonet_git/github/immonet-qa/e2e/contact.spec.ts.tsx]
[/Users/ttaskov/immonet_git/github/immonet-qa/Users/ttaskov/immonet_git/github/immonet-qa/e2e/contact.spec.ts/package.json]
[/Users/ttaskov/immonet_git/github/immonet-qa/Users/ttaskov/immonet_git/github/immonet-qa/e2e/contact.spec.ts]
[/Users/ttaskov/immonet_git/github/immonet-qa/Users/ttaskov/immonet_git/github/immonet-qa/e2e/contact.spec.ts.js]
[/Users/ttaskov/immonet_git/github/immonet-qa/Users/ttaskov/immonet_git/github/immonet-qa/e2e/contact.spec.ts.json]
[/Users/ttaskov/immonet_git/github/immonet-qa/Users/ttaskov/immonet_git/github/immonet-qa/e2e/contact.spec.ts.jsx]
[/Users/ttaskov/immonet_git/github/immonet-qa/Users/ttaskov/immonet_git/github/immonet-qa/e2e/contact.spec.ts.mjs]
[/Users/ttaskov/immonet_git/github/immonet-qa/Users/ttaskov/immonet_git/github/immonet-qa/e2e/contact.spec.ts.coffee]
[/Users/ttaskov/immonet_git/github/immonet-qa/Users/ttaskov/immonet_git/github/immonet-qa/e2e/contact.spec.ts.ts]
[/Users/ttaskov/immonet_git/github/immonet-qa/Users/ttaskov/immonet_git/github/immonet-qa/e2e/contact.spec.ts.tsx]
 
    at handle (/Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/@cypress/webpack-preprocessor/dist/index.js:212:23)
    at finalCallback (/Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:257:39)
    at /Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:306:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:304:22
    at Compiler.emitRecords (/Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:499:39)
    at /Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:298:10
    at /Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:485:14
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:482:27
    at /Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/node_modules/neo-async/async.js:2818:7
    at done (/Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/node_modules/neo-async/async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/node_modules/tapable/lib/Hook.js:154:20)
    at /Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/node_modules/webpack/lib/Compiler.js:464:33
    at /Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:143:16
    at /Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:143:16
    at /Users/ttaskov/Library/Caches/Cypress/12.17.1/Cypress.app/Contents/Resources/app/packages/server/node_modules/graceful-fs/graceful-fs.js:61:14
    at FSReqCallback.oncomplete (node:fs:198:23)

This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies

Fix the error in your code and re-run your tests.

  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        0                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  0                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     0 seconds                                                                        │
  │ Spec Ran:     contact.spec.ts                                                                  │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘

====================================================================================================

  (Run Finished)

       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✖  contact.spec.ts                            0ms        -        -        1        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  homepage.spec.ts                           0ms        -        -        1        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  login.spec.ts                              0ms        -        -        1        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  registration.spec.ts                       0ms        -        -        1        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  search.spec.ts                             0ms        -        -        1        -        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  5 of 5 failed (100%)                       0ms        -        -        5        -        -  

[7/14/2023, 9:18:21 PM] - info: Cypress process exited with code 5

[7/14/2023, 9:18:22 PM] - info: Visit https://observability.browserstack.com/builds/71vkpgdbvocrx5ri0jhshrv7vexltrkj0sqjsfku to view build report, insights, and many more debugging information all at one place!
`

**Comment by ganesh-gsk** [comment]
Hi @iwt-ttaskov,

As per your concern, 'all files of my project are deleted', I am not able to see deletion mentioned anywhere in the logs, but the error that you are getting in the logs points to the below -

A missing file or dependency
A syntax error in the file or one of its dependencies

So, could you please check if you are adding all the dependencies correctly as shown in this document - https://www.browserstack.com/docs/automate/cypress/npm-packages 

Also, is the same test working fine on your own local machine?

After checking the above things, if the issue still persists, please raise a ticket using this page https://www.browserstack.com/contact so that our team can debug more on it.

**Comment by iwt-ttaskov** [comment]
Hi @ganesh-gsk ,
I forgot to mention that I am trying the browserstack test observabilty for cypress and not the running cypress tests on browserstack. So I am trying this https://www.browserstack.com/docs/test-observability/quick-start/cypress#Tests_running_locally_or_elsewhere and not this https://www.browserstack.com/docs/automate/cypress
I am alo trying to run the tests on my local machine and after a test run the results should be sent to browserstack test observability dashboard. Hence, I do not need to add the dependencies to the browserstack.json.
By the way, I creates another simple cypress project with tests written in javascript and the test observability works as expected :)
Unfortunately, the other project that I have is a typescript project with cypress tests written in typescript and the log above is from that typescript project. You cannot see it from the logs but I can assure you that when I start the run then all files of my project are removed and therefore we get the error `This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

A missing file or dependency
A syntax error in the file or one of its dependencies`. This is because the files were deleted by the run and cypress cannot find the spec files and support file.
But as it works in my simple cypress javascript project, I would like to ask if browserstack-cypress-cli supports only javascript? Or it also supports typescript?
Thank you in advance :)

**Comment by iwt-ttaskov** [comment]
FYI:
I transpiled the cypress specs written in typescript into javascript specs and now the tests run and the files are no more deleted from my project.
So as asumed, it is the webpack that causes the issues.

**Comment by iwt-ttaskov** [comment]
I will close this ticket.
