### ISSUE TITLE
Not allowing to create Browserstack configuration file of some specific name.

### ISSUE THREAD

**Issue by kalpeshchilka** [browserstack/browserstack-cypress-cli#69]
As per the Pro Tip in the doc -https://www.browserstack.com/docs/automate/cypress/cli-reference#generate-configuration-file

> Protip: We recommend that you create multiple BrowserStack config
> files for each of your environments of test types (for example, one
> each for staging, production, regression, P1 tests etc.,) and use the
> relevant Cypress config file for each environment.

I've tried creating different BrowserStack configuration files for every environment as per doc - https://www.browserstack.com/docs/automate/cypress/cli-reference#generate-configuration-file
Running below command: 

    browserstack-cypress init browserstack.staging.json

Getting error:

    Kalpeshs-MacBook-Pro:cypress-browserstack kalpesh$ browserstack-cypress init browserstack.staging.json
    [10/10/2020, 10:56:20] - error: File already exists, delete the browserstack.json file manually. skipping...

**Comment by suryart** [comment]
I guess the file `browserstack.staging.json` already exists on your system on the given path.

Running the command for the first-time generates the file:

```bash
browserstack-cypress init browserstack.staging.json

[10/12/2020, 11:21:16 AM] - info: Creating file: /.../.../browserstack.staging.json
[10/12/2020, 11:21:16 AM] - info: BrowserStack Config File created, you can now run browserstack-cypress --config-file run

```
Listing it:

``` bash
ls -la

drwxr-xr-x  20 surya  staff    640 Oct 12 11:21 .
drwxr-xr-x  19 surya  staff    608 Sep 18 14:52 ..
-rw-r--r--   1 surya  staff   2246 Oct 12 11:21 browserstack.staging.json
```

Re-running the same would result in the error message provided:

```bash
browserstack-cypress init browserstack.staging.json
[10/12/2020, 11:21:26 AM] - error: File already exists, delete the browserstack.json file manually. skipping...
```

You'd need to remove the file before generating the same again.
