### ISSUE TITLE
browserstack local is set to null but local testing through BrowserStack is not connected

### ISSUE THREAD

**Issue by ernestosolis-discovery** [browserstack/browserstack-cypress-cli#719]
started getting this error today:
```
{
  err: null,
  status: 422,
  body: '"{\\"message\\":\\"[local] is set to true but local testing through BrowserStack is not connected. To resolve the issue or to get more info visit - [https://www.browserstack.com/question/779\\](https://www.browserstack.com/question/779//)"}"'
}
```

my browserstack local config doesn't specify using browserstack local:
```
  "connection_settings": {
    "local": null,
    "local_identifier": null,
    "local_mode": null,
    "local_config_file": null
  },
```

versions tested:
`1.25.3`
`1.26.0`

**Comment by dwhyteSA** [comment]
I'm getting a similar issue but it's been set to false! 
The terminal displays that it is set to false and then comes through with the error as stated above.

**Comment by dwhyteSA** [comment]
[18/10/2023, 11:51:26] - info: Local is set to: false (you won't be able to test localhost / private URLs)
...
[18/10/2023, 11:51:26] - error:  
{
  err: null,
  status: 422,
  body: '"{\\"message\\":\\"[local] is set to true but local testing through BrowserStack is not connected. To resolve the issue or to get more info visit - https://www.browserstack.com/question/779\\"}"'
}

**Comment by droca** [comment]
In our case we can also see in the Browserstack log when the build starts that the `local` capability is set to `false` by default

```
[10/19/2023, 1:34:34 PM] - info: Local is set to: false (you won't be able to test localhost / private URLs)
```

**Comment by ernestosolis-discovery** [comment]
@dwhyteSA  @droca 
Seems is working again, I don't get the 422 error, in case you want to retry.
tested with `browserstack-cypress-cli` versions:
- 1.26.0
- 1.25.3

**Comment by abhimanyukoul** [comment]
@ernestosolis-discovery @dwhyteSA @droca - There was an issue on the BrowserStack side which has been rectified and deployed to production.

**Comment by dwhyteSA** [comment]
Can confirm on my end that it's working as expected! Thanks @ernestosolis-discovery & @abhimanyukoul  😄

**Comment by agrawalsaurabhs** [comment]
Closing this. Regret the inconvenience caused. There was an issue on the BrowserStack side which has been fixed and deployed to production. For further queries, please reach out to us via our [Contact Us](https://www.browserstack.com/contact?utm_source=google&utm_medium=cpc&utm_platform=paidads&utm_content=668732001118&utm_campaign=Search-Brand-APAC-Intent&utm_campaigncode=Contact+9062225&utm_term=e+browserstack%20contact&gclid=Cj0KCQjw4bipBhCyARIsAFsieCzTWr5P710wynlYaJg-asPTa66BaM0e09TvGQlqFzOHboUcGIWJPUcaAh6_EALw_wcB#technical-support).
