### ISSUE TITLE
cannot add run to a queue even when thread is available

### ISSUE THREAD

**Issue by bdefore** [browserstack/browserstack-cypress-cli#74]
I'm seeing the following error when trying to run from `browserstack-cypress run`: `Build creation failed. Error: All parallel tests are currently in use, including the queued tests. Please wait to finish or upgrade your plan to add more sessions.` If I look at my dashboard, I see near Parallel Threads: 10 running, 0 queued. Not sure if the issue lies with Browserstack's API or this library.

**Comment by wati123321** [comment]
Hi @bdefore ,

Could you check the parallels you have allocated for your execution in browserstack.json file?
Kindly refer to the run settings block to check the number of parallels provided.
For eg: 
"run_settings": {
    "cypress_config_file": "./cypress.json",
    "project_name": "My sandbox project",
    "build_name": "Build no. 1",
    "parallels": "5"
}
Ref : https://www.browserstack.com/docs/automate/cypress

**Comment by bdefore** [comment]
i was able to work around this by setting parallels to `1` (from 5) although I'd still expect it to work with an empty queue.

**Comment by suryart** [comment]
Hey @bdefore 

Please feel free reach out to support@browserstack.com for assistance on this issue.
