### ISSUE TITLE
specify private npm package in "npm_dependencies"

### ISSUE THREAD

**Issue by ivan-xue-prospa** [browserstack/browserstack-cypress-cli#76]
In my project, I can use import to import some npm modules in my tests and it works fine for Cypress directly. When I tried to integrate with browserstack-cypress-cli, I got module import error  like below

`Error: Can't walk dependency graph: Cannot find module 'moment' from 'C:\Users\hello\Documents\documents\cypress_test\cypress_test_folder\cypress\pages'
    required by C:\Users\hello\Documents\documents\cypress_test\cypress_test_folder\cypress\pages\AboutYouPage.js`

Then I added these packages to "npm_dependencies" in browserstack.json, but one problem is that one of modules is Private, how can I specify the token to install this module?

**Comment by ivan-xue-prospa** [comment]
Another issue is about reporter in Cypress, I specified the reporter in cypress.json and it works fine.

`{
  "defaultCommandTimeout": 90000,
  "pageLoadTimeout": 90000,
  "video": false,
  "chromeWebSecurity": false,
  "reporter": "./reporter.js"
}`

But when I tried to run from browserstack, I got the following error

`Could not load reporter by name: ./reporter.js

We searched for the reporter in these paths:

- .\reporter.js
- .\node_modules\reporter.js

The error we received was:

Cannot find module '.\node_modules\reporter.js'`

**Comment by shawnlobo96** [comment]
Hey @ivan-xue-prospa 

When executing a test on Browserstack, the npm dependencies need to be specified in the `browserstack.json` file.

You can take a look at https://www.browserstack.com/docs/automate/cypress/npm-packages

One of the limitations is the ability to specify a private npm package. Currently, this is **not supported**.

From what you've shared, if the reporter depends on the private npm module, you will still see the same error.

**Comment by ivan-xue-prospa** [comment]
Hi @shawnlobo96 Thanks for your explaination.

**Comment by theVoogie** [comment]
> Another issue is about reporter in Cypress, I specified the reporter in cypress.json and it works fine.
> 
> `{ "defaultCommandTimeout": 90000, "pageLoadTimeout": 90000, "video": false, "chromeWebSecurity": false, "reporter": "./reporter.js" }`
> 
> But when I tried to run from browserstack, I got the following error
> 
> Could not load reporter by name: ./reporter.js
> 
> We searched for the reporter in these paths:
> 
> * .\reporter.js
> * .\node_modules\reporter.js
> 
> The error we received was:
> 
> Cannot find module '.\node_modules\reporter.js'

Did you manage to make it work @ivan-xue-prospa ?
