### ISSUE TITLE
browserstack.json must contain auth object even if relying on environment variables

### ISSUE THREAD

**Issue by bdefore** [browserstack/browserstack-cypress-cli#77]
If relying on i.e. BROWSERSTACK_USERNAME environment variable, browserstack.json must contain `auth: {}` or else this error occurs: `Cannot set property 'username' of undefined`. Would be better if it worked as well without an empty object present.

**Comment by Namrata-m13** [comment]
@bdefore A fix for this has been deployed. Let us know if it works for you as well.

**Comment by bdefore** [comment]
i'm still seeing 1.5.1 as the latest in npm. is there another release you'd like me to try?

**Comment by suryart** [comment]
Hey @bdefore,

This issue is addressed in the v1.5.2 release.
