### ISSUE TITLE
Uploading .npmrc file is failing

### ISSUE THREAD

**Issue by ivan-xue-prospa** [browserstack/browserstack-cypress-cli#81]
For our projects, we need to install some private mode modules, so I updated the archiver.js as following to zip .npmrc file

`Constants.allowedFileTypes.forEach(fileType => {
      archive.glob(`**/*.${fileType}`, { cwd: cypressFolderPath, matchBase: true, ignore: ignoreFiles, dot: true });
    });`

But the tests failed due to the following error

`error: Please make sure you are uploading files with extension .js, .json, .txt, .ts, .feature, .features, .pdf, .jpg, .jpeg, .png, or .zip`

Is it possible that we can update the upload API to allow dot files?

**Comment by ivan-xue-prospa** [comment]
If we can make this change, I will create one PR for this.

**Comment by suryart** [comment]
Hey @ivan-xue-prospa,

This issue is addressed in the v1.5.2 release.
