### ISSUE TITLE
Tool doesn't support Cypress experimental features

### ISSUE THREAD

**Issue by dkryshtopenko** [browserstack/browserstack-cypress-cli#93]
experimental features are enabled:
```  
"experimentalFetchPolyfill": true,
  "experimentalNetworkStubbing": true,
```
I run my tests using cy.route2 on Browserstack and get the next error:
<img width="898" alt="Screenshot 2020-11-23 at 2 02 19 PM" src="https://user-images.githubusercontent.com/72011031/99959884-8255c180-2d94-11eb-98a3-e8821c33840e.png">

**Locally works fine.**

What is workaround? I need to use cy.route2 api method for mocking HTTP requests.

**Comment by dkryshtopenko** [comment]
My `browserstack.json` file
`{
    "auth": {
        "username": "*",
        "access_key": "*"
    },
    "browsers": [
        {
            "browser": "chrome",
            "os": "Windows 10",
            "versions": [
                "latest"
            ]
        }
    ],
    "run_settings": {
        "cypress_config_file": "./cypress.json",
        "project_name": "project-name",
        "build_name": "build-name",
        "exclude": [

        ],
        "parallels": "1",
        "npm_dependencies": {
            "cypress-file-upload": "^4.1.1",
            "cypress-localstorage-commands": "^1.2.4",
            "cypress-multi-reporters": "^1.4.0",
            "faker": "^5.1.0",
            "mochawesome": "^6.2.1"
        },
        "package_config_options": {

        }
    },
    "connection_settings": {
        "local": true,
        "local_identifier": null
    },
    "disable_usage_reporting": false
}
`

**Comment by wati123321** [comment]
route2 is released in Cypress v5.x as a feature. We are still on Cypress v4.x on BrowserStack so we don’t currently support this. Once we start supporting Cypress 5, you will be able to use this.

**Comment by dkryshtopenko** [comment]
@wati123321 6.0 have just released. Do it 👍

**Comment by karanshah-browserstack** [comment]
Hi, This should be fixed in v1.6.0 which we released yesterday. Please feel free to reach out to us if you still feel any issues .

**Comment by dkryshtopenko** [comment]
@karanshah-browserstack what is Cypress version in BrowserStack now?

**Comment by karanshah-browserstack** [comment]
@dkryshtopenko We currently support 5.5.0 Cypress version and soon will start supporting v6 too.

**Comment by karanshah-browserstack** [comment]
You can follow https://www.browserstack.com/docs/automate/cypress/supported-versions on how to use different versions.
